### ISSUE TITLE
"image/jxl" content-type is ignored

### ISSUE THREAD

**Issue by l29ah** [un-def/tinystash#1]
Repro: `curl -s https://tinystash.undef.im/upload/file -H app-id:w3crapcli -H content-type:image/jxl --data-binary @IMG_20240813_144015_DRO.jxl`

Resulting URL returns `application/octet-stream` content-type.

**Comment by un-def** [comment]
Thanks for the report.

Fixed, new uploads will respect `image/jxl` and `image/jxr` media types, for existing uploads media type can be overridden via the `mt=` query parameter (that is, `https://tinystash.undef.im/il/<tiny_id>.jxl?mt=image/jxl`)
